resourcePackages:
  - org.apache.archiva.redback.rest.api

prettyPrint: true
cacheTTL: 0
openAPI:
  components:
    securitySchemes:
      BearerAuth:
        type: http
        scheme: bearer
        bearerFormat: JWT
      BasicAuth:
        type: http
        scheme: basic

  servers:
    - url: /archiva/api/v2/redback
      description: Base URL Version 2 API
    - url: /archiva/redbackServices
      description: Base URL Version 1 API
  tags:
    - name: v2
      description: Version 2 REST API
    - name: v2/Authentication
      description: Authentication operations for Login and token refresh
    - name: v2/Groups
      description: Group operations
    - name: v1
      description: Version 1 REST API (deprecated)

  info:
    version: '3.0'
    title: Apache Archiva Redback REST API
    description: 'This is the Apache Archiva Redback REST API documentation'
    termsOfService: https://archiva.apache.org
    contact:
      email: users@archiva.apache.org
      url: https://archiva.apache.org/index.html
    license:
      name: Apache 2.0
      url: http://www.apache.org/licenses/LICENSE-2.0.html